# Autogenerated with SMOP 
from smop.core import *
# getStore.m

    
@function
def getStore(problem=None,x=None,storedb=None,*args,**kwargs):
    varargin = getStore.varargin
    nargin = getStore.nargin

    error('This file was removed from Manopt. Please use the StoreDB class.')
    return store
    
if __name__ == '__main__':
    pass
    