# Autogenerated with SMOP 
from smop.core import *
# purgeStoredb.m

    
@function
def purgeStoredb(storedb=None,storedepth=None,*args,**kwargs):
    varargin = purgeStoredb.varargin
    nargin = purgeStoredb.nargin

    error('This file was removed from Manopt. Please use the StoreDB class.')
    return storedb
    
if __name__ == '__main__':
    pass
    