# Autogenerated with SMOP 
from smop.core import *
# setStore.m

    
@function
def setStore(problem=None,x=None,storedb=None,store=None,*args,**kwargs):
    varargin = setStore.varargin
    nargin = setStore.nargin

    error('This file was removed from Manopt. Please use the StoreDB class.')
    return storedb
    
if __name__ == '__main__':
    pass
    