# Autogenerated with SMOP 
from smop.core import *
# manopt_version.m

    
@function
def manopt_version(*args,**kwargs):
    varargin = manopt_version.varargin
    nargin = manopt_version.nargin

    # Returns the version of the Manopt package you are running, as a vector.
    
    # function [version, released] = manopt_version()
    
    # version(1) is the primary version number.
# released is the date this version was released, in the same format as the
# date() function in Matlab.
    
    version=matlabarray(cat(3,0,0))
# manopt_version.m:10
    released='12-Nov-2016'
# manopt_version.m:11
    return version,released
    
if __name__ == '__main__':
    pass
    