# Autogenerated with SMOP 
from smop.core import *
# multisqnorm.m

    
@function
def multisqnorm(A=None,*args,**kwargs):
    varargin = multisqnorm.varargin
    nargin = multisqnorm.nargin

    # Returns the squared Frobenius norms of the slices of a 3D matrix.
    
    # function sqnorm = multisqnorm(A)
    
    # Given a 3-dimensional matrix A of size n-by-m-by-N, returns a column
# vector of length N such that sqnorm(i) = norm(A(:, :, i), 'fro')^2.
    
    # See also: multiprod multitransp multitrace norms
    
    # This file is part of Manopt: www.manopt.org.
# Original author: Nicolas Boumal, June 17, 2015.
# Contributors: 
# Change log:
    
    assert_(ndims(A) <= 3,cat('multisqnorm is only well defined for matrix arrays of 3 ','or less dimensions.'))
    n,m,N=size(A,nargout=3)
# multisqnorm.m:20
    
    sqnorm=sum(reshape(A,dot(n,m),N) ** 2,1).T
# multisqnorm.m:23
    return sqnorm
    
if __name__ == '__main__':
    pass
    